all:

  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:

    local:

      hosts:

        localhost:
          ansible_connection: local

    powerscale:

      hosts:

        powerscale-prod:
          ansible_host: 10.10.10.10