---
- name: Provisionar buckets PowerScale
  hosts: localhost
  connection: local

  vars_files:
    - ../../catalog/buckets.yml

  tasks:

    - name: Mostrar buckets
      ansible.builtin.debug:
        var: buckets
