---
- name: Reconciliação dinâmica
  hosts: localhost
  connection: local

  vars_files:
    - vars/buckets.yml

  tasks:

    - name: Consultar API
      ansible.builtin.uri:
        url: https://jsonplaceholder.typicode.com/users
        method: GET
        return_content: true

      register: api_result

    - name: Extrair nomes existentes
      ansible.builtin.set_fact:
        existing_buckets: >-
          {{
            api_result.json
            | map(attribute='username')
            | list
          }}

    - name: Mostrar existentes
      ansible.builtin.debug:
        var: existing_buckets

    - name: Criar buckets ausentes
      ansible.builtin.uri:
        url: https://jsonplaceholder.typicode.com/posts
        method: POST

        body_format: json

        body:
          bucket_name: "{{ item.name }}"
          owner: "{{ item.owner }}"
          retention: "{{ item.retention }}"

        status_code:
          - 201

      when: item.name not in existing_buckets

      loop: "{{ buckets }}"

      register: resultado

    - name: Mostrar criação
      ansible.builtin.debug:
        var: resultado.results
