---
- name: Provisionar buckets fake
  hosts: localhost
  connection: local

  vars_files:
    - vars/buckets.yml

  tasks:

    - name: Simular criação bucket via API
      ansible.builtin.uri:
        url: https://jsonplaceholder.typicode.com/posts
        method: POST

        body_format: json

        body:
          bucket_name: "{{ item.name }}"
          owner: "{{ item.owner }}"
          retention: "{{ item.retention }}"

        return_content: true

        status_code:
          - 201

      register: resultado

      loop: "{{ buckets }}"

    - name: Mostrar retorno
      ansible.builtin.debug:
        var: resultado.results
