---
- name: Teste de variáveis
  hosts: localhost
  connection: local

  vars:
    sistema: SAP01
    ambiente: prod
    retention: 7y

  tasks:

    - name: Mostrar informações
      ansible.builtin.debug:
        msg:
          - "Sistema: {{ sistema }}"
          - "Ambiente: {{ ambiente }}"
          - "Retenção: {{ retention }}"
