- name: Teste REST API
  hosts: localhost
  connection: local

  tasks:

    - name: Consultar API pública
      ansible.builtin.uri:
        url: https://api.github.com
        method: GET
        return_content: true

      register: resultado

    - name: Mostrar retorno
      ansible.builtin.debug:
        var: resultado.json
