---
- name: Extrair campo JSON
  hosts: localhost
  connection: local

  tasks:

    - name: Chamar API
      ansible.builtin.uri:
        url: https://api.github.com
        method: GET
        return_content: true

      register: api

    - name: Mostrar URL atual user
      ansible.builtin.debug:
        msg: "{{ api.json.current_user_url }}"
