buckets:

  - name: sap-batch-prod
    owner: team-finance
    retention: 7y

  - name: edi-online-prod
    owner: integration-team
    retention: 1y

  - name: wms-prod
    owner: logistics-team
    retention: 5y