---
- name: Teste condição
  hosts: localhost
  connection: local

  vars:
    ambiente: prod

  tasks:

    - name: Executar apenas em produção
      ansible.builtin.debug:
        msg: "Deploy em produção"

      when: ambiente == "prod"
