- name: Criar diretório teste
  hosts: localhost
  connection: local

  tasks:

    - name: Criar pasta
      ansible.builtin.file:
        path: ~/ansible-test
        state: directory
        mode: "0755"
