- name: Diretório dinâmico
  hosts: localhost
  connection: local

  vars:
    sistema: SAP01
    ambiente: prod

  tasks:

    - name: Criar diretório dinâmico
      ansible.builtin.file:
        path: "~/{{ sistema }}-{{ ambiente }}"
        state: directory
        mode: "0755"
