---
- name: Criar múltiplos diretórios
  hosts: localhost
  connection: local

  vars:
    sistemas:
      - SAP01
      - EDI01
      - WMS01

  tasks:

    - name: Criar diretórios
      ansible.builtin.file:
        path: "~/{{ item }}"
        state: directory
        mode: "0755"

      loop: "{{ sistemas }}"
